import os
os.system("clear")
os.system("echo 'downloading ...'|lolcat")
print(For.RED+"downloading ...")
os.system("pip install colorama")
os.system("pip install pyngrok")
os.system("pip install subprocess")
os.system("apt update")
os.system("pkg install python")
os.system("unzip pubg.zip")
os.system("cd pubg")
os.system("python PUBG.py")
